#Sets the name of the CamelContext
camel:
  springboot:
    name: moviebkg-movie-svc
    use-mdc-logging: true
#Configure log level
logging:
  level:
    com:
      zaxxer: INFO
    org.springframework: INFO
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: INFO

#Configuring servlet context path. Path from which API's related to this microservice are served from
server:
  servlet:
    context-path: /moviesvc
  port: 8080

#Configuring secret and expiration for jwt token
application:
  security:
    jwt:
      secret-key: a37931c235406b0a24a00317e915a0f3e3b45a40b8282db1d916179cf77ce5a1a3d2d57d2f1ed
      expiration: 3600000

#Configuring for enabling and disabling jwt token flow
token:
  disabled: false

#Configuring queue type.
mbkg:
  queue-type: activemq